// Generated by scripts/generate-waitlist-config.cjs from WAITLIST_WEBHOOK_URL.
// This endpoint is public browser configuration; no other .env values are exported.
window.ARN_CONFIG = Object.assign(window.ARN_CONFIG || {}, {
  "waitlistWebhookUrl": "https://n8n.arngct.org/webhook/saniatrypad"
});
